import { StyleSheet } from "react-native";
import { useMemo } from "react";
import { useTheme, type Palette } from "../theme";

const createStyles = (C: Palette) => StyleSheet.create({
  screen: { flex: 1, backgroundColor: C.bg },
  content: { padding: 22, paddingTop: 10, paddingBottom: 36, gap: 24 },
  toolbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  row: { flexDirection: "row", alignItems: "center", gap: 10 },
  wrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  grow: { flex: 1 },
  hero: {
    backgroundColor: C.hero,
    borderRadius: 26,
    padding: 25,
    gap: 13,
    overflow: "hidden",
  },
  eyebrow: {
    color: C.blue,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  title: {
    fontSize: 38,
    lineHeight: 43,
    fontWeight: "700",
    letterSpacing: -1.7,
    color: C.ink,
  },
  intro: { fontSize: 14, lineHeight: 22, color: C.body, maxWidth: 510 },
  soft: { padding: 15, backgroundColor: C.soft, borderRadius: 15, gap: 6 },
  label: { fontSize: 12, fontWeight: "700", color: C.ink },
  small: { fontSize: 12, lineHeight: 18, color: C.muted },
  sectionTitle: {
    fontSize: 23,
    fontWeight: "700",
    letterSpacing: -0.7,
    color: C.ink,
  },
  link: { color: C.blue, fontSize: 13, fontWeight: "700" },
  tabRow: {
    flexDirection: "row",
    gap: 22,
    borderBottomColor: C.line,
    borderBottomWidth: 1,
  },
  textTab: {
    minHeight: 44,
    paddingVertical: 12,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  textTabActive: { borderBottomColor: C.blue },
  search: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderRadius: 14,
    paddingHorizontal: 14,
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.line,
    minHeight: 49,
  },
  searchInput: {
    flex: 1,
    color: C.ink,
    fontSize: 14,
    paddingVertical: 14,
    outlineWidth: 0,
  },
  chip: {
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 13,
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.line,
    justifyContent: "center",
  },
  chipActive: { backgroundColor: C.inverse, borderColor: C.inverse },
  chipText: { fontSize: 12, fontWeight: "600", color: C.body },
  chipTextActive: { color: C.onInverse },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    rowGap: 20,
    columnGap: 0,
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  postCard: {
    backgroundColor: C.white,
    borderRadius: 23,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: C.line,
  },
  image: { width: "100%", backgroundColor: C.image },
  imageEmpty: {
    minHeight: 200,
    backgroundColor: C.pale,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  imageBadges: {
    position: "absolute",
    top: 13,
    left: 13,
    right: 13,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  imageBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: C.imageBadge,
  },
  badgeText: { fontSize: 10, fontWeight: "700", color: C.ink },
  postBody: { padding: 17, gap: 12 },
  postTitle: {
    fontSize: 22,
    lineHeight: 27,
    letterSpacing: -0.65,
    fontWeight: "700",
    color: C.ink,
  },
  authorButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    minHeight: 44,
    flex: 1,
  },
  authorName: { fontSize: 12, color: C.ink, fontWeight: "700" },
  iconButton: {
    minWidth: 44,
    minHeight: 44,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 13,
  },
  section: { gap: 16 },
  card: {
    padding: 20,
    backgroundColor: C.white,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: C.line,
    gap: 15,
  },
  body: { color: C.body, lineHeight: 23, fontSize: 14 },
  nav: {
    borderTopWidth: 1,
    borderTopColor: C.line,
    flexDirection: "row",
    backgroundColor: C.white,
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 9,
    gap: 4,
  },
  navItem: {
    minHeight: 55,
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    borderRadius: 14,
  },
  navActive: { backgroundColor: C.pale },
  navLabel: { fontSize: 10, fontWeight: "600", color: C.muted },
  createNav: {
    backgroundColor: C.accent,
    height: 34,
    width: 42,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  toast: {
    position: "absolute",
    bottom: 90,
    left: 20,
    right: 20,
    backgroundColor: C.inverse,
    borderRadius: 15,
    padding: 15,
    gap: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  toastText: { color: C.onInverse, fontSize: 13, lineHeight: 19, flex: 1 },
  profileHero: {
    backgroundColor: C.profile,
    padding: 25,
    borderRadius: 25,
    gap: 17,
  },
  divider: { height: 1, backgroundColor: C.line },
  choice: {
    backgroundColor: C.white,
    padding: 15,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: C.line,
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    minHeight: 60,
  },
  choiceActive: { borderColor: C.selectionBorder, backgroundColor: C.pale },
  upload: {
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: C.selectionBorder,
    backgroundColor: C.pale,
    borderRadius: 20,
    minHeight: 155,
    alignItems: "center",
    justifyContent: "center",
    padding: 22,
    gap: 10,
  },
  unread: { width: 7, height: 7, borderRadius: 4, backgroundColor: C.accent },
});

export function useSocialStyles() {
  const { C } = useTheme();
  return useMemo(() => createStyles(C), [C]);
}
